Repository priyanshbalyan/discord-file-storage, pull requests merged in 2021-10, with the labels that each got.

#3 Added Meaningful Comment
  fs.py
Labels: Hacktoberfest, hacktoberfest-accepted

#5 Fixes #4
  fs.py
Labels: Hacktoberfest, hacktoberfest-accepted

#7 Fixes #6
  fs.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberest-accepted

#9 Fixes #8
  fs.py
Labels: documentation, Hacktoberfest, hacktoberfest-accepted, hacktoberest-accepted
